Resources:
  TasksAPITable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}  # as in serverless.yml
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK  # partition key
          AttributeType: S
        - AttributeName: SK  # sort key
          AttributeType: S
        - AttributeName: GS1PK   # global secondary index partition key
          AttributeType: S
        - AttributeName: GS1SK  # global secondary index sort key
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GS1
          KeySchema:
            - AttributeName: GS1PK
              KeyType: HASH
            - AttributeName: GS1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL